{
 "title": "morozovav",
 "time": { "from": "2021-02-20T18:39:55.199Z", "to": "2021-02-20T18:48:39.983Z" },
 "panels": [
  {
   "title": "RPS",
   "type": "graph",
   "gridPos": { "h": 6, "w": 10, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (container, method, uri) (rate(http_server_requests_seconds_count[1m]))",
     "legendFormat": "{{container}} {{method}} {{uri}}"
    }
   ]
  },
  {
   "title": "Latency 0.5",
   "type": "graph",
   "gridPos": { "h": 6, "w": 7, "x": 10, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.5, \r\n      sum by (le, container, uri) \r\n         (rate(http_server_requests_seconds_bucket[1m]))\r\n) * 1000",
     "legendFormat": "{{container}} {{uri}}"
    }
   ]
  },
  {
   "title": "Latency 0.95",
   "type": "graph",
   "gridPos": { "h": 6, "w": 7, "x": 17, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.95, \r\n      sum by (le, container, uri) \r\n         (rate(http_server_requests_seconds_bucket[1m]))\r\n) * 1000",
     "legendFormat": "{{container}} {{uri}}"
    }
   ]
  },
  {
   "title": "Errors",
   "type": "graph",
   "gridPos": { "h": 6, "w": 10, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (container, method, uri) (increase(http_server_requests_seconds_count{status=~\"5.+\"}[1m]))",
     "legendFormat": "{{container}} {{method}} {{uri}}"
    }
   ]
  },
  {
   "title": "Latency 1",
   "type": "graph",
   "gridPos": { "h": 6, "w": 7, "x": 10, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(1.0, \r\n      sum by (le, container, uri) \r\n         (rate(http_server_requests_seconds_bucket[1m]))\r\n) * 1000",
     "legendFormat": "{{container}} {{uri}}"
    }
   ]
  },
  {
   "title": "Latency 0.99",
   "type": "graph",
   "gridPos": { "h": 6, "w": 7, "x": 17, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, \r\n      sum by (le, container, uri) \r\n         (rate(http_server_requests_seconds_bucket[1m]))\r\n) * 1000",
     "legendFormat": "{{container}} {{uri}}"
    }
   ]
  },
  {
   "title": "RPS Ingress",
   "type": "graph",
   "gridPos": { "h": 6, "w": 10, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (path) (rate(nginx_ingress_controller_request_duration_seconds_count[1m]))",
     "legendFormat": "{{path}}"
    }
   ]
  },
  {
   "title": "Latency 0.5 Ingress",
   "type": "graph",
   "gridPos": { "h": 6, "w": 7, "x": 10, "y": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.5, \r\n      sum by (le, path) \r\n         (rate(nginx_ingress_controller_request_duration_seconds_bucket[1m]))\r\n) * 1000",
     "legendFormat": "{{path}}"
    }
   ]
  },
  {
   "title": "Latency 0.95 Ingress",
   "type": "graph",
   "gridPos": { "h": 6, "w": 7, "x": 17, "y": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.95, \r\n      sum by (le, path) \r\n         (rate(nginx_ingress_controller_request_duration_seconds_bucket[1m]))\r\n) * 1000",
     "legendFormat": "{{path}}"
    }
   ]
  },
  {
   "title": "Errors Ingress",
   "type": "graph",
   "gridPos": { "h": 6, "w": 10, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (path, status) (increase(nginx_ingress_controller_request_duration_seconds_count{status=~\"[4|5].+\"}[1m]))",
     "legendFormat": "{{path}} {{status}}"
    }
   ]
  },
  {
   "title": "Latency 1 Ingress",
   "type": "graph",
   "gridPos": { "h": 6, "w": 7, "x": 10, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(1.0, \r\n      sum by (le, path) \r\n         (rate(nginx_ingress_controller_request_duration_seconds_bucket[1m]))\r\n) * 1000",
     "legendFormat": "{{path}}"
    }
   ]
  },
  {
   "title": "Latency 0.99 Ingress",
   "type": "graph",
   "gridPos": { "h": 6, "w": 7, "x": 17, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, \r\n      sum by (le, path) \r\n         (rate(nginx_ingress_controller_request_duration_seconds_bucket[1m]))\r\n) * 1000",
     "legendFormat": "{{path}}"
    }
   ]
  }
 ]
}